[package]
name = "rust_practice"
version = "0.1.0"
edition = "2021"
authors = ["Atri Hegde <atri@hegdeatri.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "9.1.0"
rand = "0.8.1"