#!/bin/sh

cargo new $1

cat <<EOT > "$1"/src/main.rs
//

pub struct Solution;

impl Solution {

}

fn main() {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn case1() {

    }
}


EOT
